{% set name = "sse-starlette" %}
{% set version = "2.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 54470d5f19274aeed6b2d473430b08b4b379ea851d953b11d7f1c4a2c118b419

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pdm-backend
    - pip
  run:
    - python
    - anyio >=4.7.0
    - starlette >=0.41.3
test:
  imports:
    - sse_starlette
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/sysid/sse-starlette
  summary: SSE plugin for Starlette
  description: SSE plugin for Starlette
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/sysid/sse-starlette
  doc_url: https://github.com/sysid/sse-starlette/blob/main/README.md


extra:
  recipe-maintainers:
    - dhirschfeld
    - cyprienc
