{% set name = "sse-starlette" %}
{% set version = "1.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sse-starlette-{{ version }}.tar.gz
  sha256: 9a58f8abc020cc158ac834f9667f4cb37d09d5d3b78c81c013bc768369abeca2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - starlette

test:
  imports:
    - sse_starlette
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sysid/sse-starlette
  summary: SSE plugin for Starlette
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/sysid/sse-starlette


extra:
  recipe-maintainers:
    - dhirschfeld
    - cyprienc
